import type { ApplicationSnapshot } from '../domain';

const megabyte = 1024 * 1024;

export function createFixtureSnapshot(): ApplicationSnapshot {
  return {
    activity: [
      {
        action: 'restart',
        id: 'activity-1',
        occurredAt: '12:31:04',
        subject: 'api-local/api',
        successful: true,
      },
      {
        action: 'stop',
        id: 'activity-2',
        occurredAt: '11:58:20',
        subject: 'api-local/mailpit',
        successful: true,
      },
    ],
    capabilities: {
      lifecycleActions: true,
      logs: true,
    },
    connection: 'connected',
    globalStopInProgress: false,
    globalStopProgress: null,
    globalStopReport: null,
    preferences: {
      language: navigator.language.toLowerCase().startsWith('pl') ? 'pl' : 'en',
      theme: 'system',
    },
    projects: [
      {
        active: true,
        id: 'storefront',
        name: 'Sklep lokalny',
        profiles: [],
        services: [
          {
            bulkSelected: true,
            cpuPercent: 1.8,
            id: 'storefront-web',
            included: true,
            memoryBytes: 284 * megabyte,
            name: 'web',
            ports: ['3000:3000'],
            profiles: [],
            status: 'running',
          },
          {
            bulkSelected: false,
            cpuPercent: 0.2,
            id: 'storefront-api',
            included: true,
            memoryBytes: 96 * megabyte,
            name: 'api',
            ports: ['3001:3000'],
            profiles: [],
            status: 'healthy',
          },
          {
            bulkSelected: true,
            cpuPercent: 1.1,
            id: 'storefront-postgres',
            included: true,
            memoryBytes: 512 * megabyte,
            name: 'postgres',
            ports: ['5432:5432'],
            profiles: [],
            status: 'running',
          },
          {
            bulkSelected: false,
            cpuPercent: 0.4,
            id: 'storefront-redis',
            included: true,
            memoryBytes: 128 * megabyte,
            name: 'redis',
            ports: ['6379:6379'],
            profiles: [],
            status: 'running',
          },
        ],
      },
      {
        active: true,
        id: 'api-local',
        name: 'API lokalne',
        profiles: [],
        services: [
          {
            bulkSelected: false,
            cpuPercent: 0.7,
            id: 'api-local-web',
            included: true,
            memoryBytes: 180 * megabyte,
            name: 'web',
            ports: ['8080:3000'],
            profiles: [],
            status: 'running',
          },
          {
            bulkSelected: true,
            cpuPercent: 1.2,
            id: 'api-local-api',
            included: true,
            memoryBytes: 256 * megabyte,
            name: 'api',
            ports: ['3000:3000'],
            profiles: [],
            status: 'healthy',
          },
          {
            bulkSelected: false,
            cpuPercent: null,
            id: 'api-local-postgres',
            included: true,
            memoryBytes: null,
            name: 'postgres',
            ports: ['5432:5432'],
            profiles: [],
            status: 'stopped',
          },
          {
            bulkSelected: false,
            cpuPercent: 0,
            id: 'api-local-redis',
            included: true,
            memoryBytes: 12 * megabyte,
            name: 'redis',
            ports: ['6379:6379'],
            profiles: [],
            status: 'starting',
          },
          {
            bulkSelected: false,
            cpuPercent: null,
            id: 'api-local-mailpit',
            included: true,
            memoryBytes: null,
            name: 'mailpit',
            ports: ['8025:8025'],
            profiles: [],
            status: 'stopped',
          },
        ],
      },
      {
        active: false,
        id: 'docs-preview',
        name: 'Dokumentacja',
        profiles: [],
        services: [
          {
            bulkSelected: true,
            cpuPercent: null,
            id: 'docs-preview-site',
            included: true,
            memoryBytes: null,
            name: 'site',
            ports: ['4173:4173'],
            profiles: [],
            status: 'stopped',
          },
        ],
      },
    ],
    standaloneContainers: [
      {
        bulkSelected: false,
        cpuPercent: 0.1,
        id: 'standalone-minio',
        included: true,
        memoryBytes: 148 * megabyte,
        name: 'local-minio',
        ports: ['9000:9000', '9001:9001'],
        profiles: [],
        status: 'running',
      },
      {
        bulkSelected: false,
        cpuPercent: null,
        id: 'standalone-mailhog',
        included: true,
        memoryBytes: null,
        name: 'legacy-mailhog',
        ports: ['8026:8025'],
        profiles: [],
        status: 'stopped',
      },
    ],
  };
}

export const fixtureLogs: Record<string, string[]> = {
  'api-local-api': [
    '[12:36:14] [INFO] Starting api service...',
    '[12:36:15] [INFO] Loading environment from .env',
    '[12:36:15] [INFO] Connecting to database...',
    '[12:36:16] [INFO] Database connection ready',
    '[12:36:16] [INFO] Running migrations...',
    '[12:36:17] [INFO] Migrations completed',
    '[12:36:17] [INFO] Server listening on :3000',
    '[12:36:21] [INFO] GET /api/health 200',
    '[12:36:28] [INFO] GET /api/users 200',
    '[12:36:32] [INFO] POST /api/login 201',
    '[12:36:45] [INFO] GET /api/health 200',
  ],
};
